### ISSUE TITLE
Support for Rails < 6?

### ISSUE THREAD

**Issue by thoughtafter** [themilkman/jquery-tablesorter-rails#10]
I tried upgrading a Rails 5.2.2 project to jquery-tablesorter 1.27.0 and got:

````
Bundler could not find compatible versions for gem "railties":
  In Gemfile:
    jquery-tablesorter (~> 1.27.0) was resolved to 1.27.0, which depends on
      railties (>= 3.2, ~> 6.0.0)

    rails (~> 5.2.2) was resolved to 5.2.3.rc1, which depends on
      railties (= 5.2.3.rc1)
````
Is this only going to be supported for Rails 6 moving forward? If so that should probably be documented.

**Comment by themilkman** [comment]
Oh snap, I'll try to look into this soon, thanks for the report. It was intended to keep working with Rails 5.

**Comment by themilkman** [comment]
Please test the current version 1.27.1.
