### ISSUE TITLE
Set theme

### ISSUE THREAD

**Issue by Mottie** [themilkman/jquery-tablesorter-rails#2]
Could you include a note in the documentation about changing the `theme` option if you include a specific css theme ([source](http://stackoverflow.com/questions/22307190/why-is-jquery-tablesorter-not-working-in-my-rails-4-app?noredirect=1#comment33935294_22307190)).

> Two things were causing my issue: 1. I hadn't loaded the appropriate css file into my assets (which would have been "theme.default.css" since I wasn't specifying a theme in my call to the tablesorter function). This would be some handy information to list in the instructions, IMO. 2. For some strange reason (and more to the core of the issue), my app isn't recognizing multiple "jQuery(document).ready" calls from multiple script files. 

I know nothing about rails, so I don't know if the second part of that issue needs to be addressed as well.

Thanks!

**Comment by kevle** [comment]
For me only the default theme works, as the automatically added class for the table still is "tablesorter-default". Could you expand the documentation to detail where else I have to change something in order to change the theme?

Warm regards.

**Comment by themilkman** [comment]
Hi @kevle,

did you include the bootstrap-theme in the application.css as documented? Did you configure the tablesorter-theme as explained in Mottie's documentation [(here)](https://mottie.github.io/tablesorter/docs/example-widget-bootstrap-theme.html)? What does change, what doesn't?

If yes, could you provide your application.css, application.js and an HTML/template example? 

Cheers
Erik

**Comment by kevle** [comment]
Hi @themilkman,

thank you very much for pointing me in the right direction. I have not studied Mottie's documentation well enough. In order to use the bootstrap theme one apparently also needs to specify the widgets and headerTemplate options.

This works for me:
```javascript
  $("table").tablesorter({
    // this will apply the bootstrap theme if "uitheme" widget is included
    // the widgetOptions.uitheme is no longer required to be set
    theme : "bootstrap",

    headerTemplate : '{content} {icon}', // new in v2.7. Needed to add the bootstrap icon!

    // widget code contained in the jquery.tablesorter.widgets.js file
    // use the zebra stripe widget if you plan on hiding any rows (filter widget)
    widgets : [ "uitheme"]
});
```

Regards & a big thank you.

**Comment by themilkman** [comment]
Glad to hear that it works now :-)
