### ISSUE TITLE
Rails sprockets unable to find `'jquery-tablesorter/theme.bootstrap`

### ISSUE THREAD

**Issue by onebree** [themilkman/jquery-tablesorter-rails#4]
**Rails 4.2.0, Ruby 1.9.3, Haml 4.0.6, Bootstrap 3.3.4**

I followed your README, and even tried a different theme, according to your demo (theme.blue). Are there additional files I need to install? To my understanding, the gem is supposed to contain the JS files needed.

```
A Sprockets::FileNotFound occurred in contacts#index:

  couldn't find file 'jquery-tablesorter/theme.bootstrap
'jquery-tablesorter/theme.bootstrap'
  (in /var/www/rails/hosted/hpbxgui/app/assets/stylesheets/application.css.scss:11)
  app/views/layouts/application.html.haml:10:in `_app_views_layouts_application_html_haml___4437235674204882235_65511980'
```

**Comment by onebree** [comment]
I am closing this issue. I found an answer on SO that helped. Silly me, forgetting to restart the rails server!

http://stackoverflow.com/a/12882832/3373470

**Comment by themilkman** [comment]
Glad to see you could solve the problem.

Cheers!

**Comment by onebree** [comment]
While that problem is solved, I have another.

I do not know if I need further configuration, but my table looks like the following
![screenshot from 2015-04-29 13 45 16](https://cloud.githubusercontent.com/assets/9038433/7397397/043ebd32-ee76-11e4-9180-a9c1f49ee9ae.png)

There is no padding or styling. As instructed in the README, I added all lines to necessary files, even the "individual" JS files (which did nothing).

Right now, we use: [sorttable.js](http://www.kryogenix.org/code/browser/sorttable/), but it is not working for us right now. It works, but once you change the page, the sorting goes away.

I would ideally like our tables to look like codepen.io/Mottie/pen/Ltzpi, but without the purple, hovers, or highlighted cells upon sorting.
