### ISSUE TITLE
Outdent error when trying to set widgetOptions

### ISSUE THREAD

**Issue by shazam1453** [themilkman/jquery-tablesorter-rails#9]
Hello!

I'm able to call the plugin to set themes and filters for my rails project, but as soon as I try to set the widget options Rails starts throwing an outdent error.  All I'm trying to do right now is add a button to reset my filters, and after reading through the available documentation on tablesorter I'm not 100% sure what's causing this to crash.  

Error message from Rails:

  Rendered manage_devices/load.html.erb within layouts/application (148.4ms)
Completed 500 Internal Server Error in 577ms (ActiveRecord: 9.9ms)

  
ActionView::Template::Error (SyntaxError: [stdin]:19:3: unmatched OUTDENT):
    3: <head>
    4:   <title>ArgusDeviceManager</title>
    5:   <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track' => true %>
    6:   <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
    7:   <%= csrf_meta_tags %>
    8: </head>
    9: 
  
(execjs):7539:8
(execjs):7545:14
app/views/layouts/application.html.erb:6:in `_app_views_layouts_application_html_erb__396433957700005420_70136231785980'

Application.js:

```
// This is a manifest file that'll be compiled into application.js, which will include all the files
// listed below.
//
// Any JavaScript/Coffee file within this directory, lib/assets/javascripts, or any plugin's
// vendor/assets/javascripts directory can be referenced here using a relative path.
//
// It's not advisable to add code directly here, but if you do, it'll appear at the bottom of the
// compiled file. JavaScript code in this file should be added after the last require_* statement.
//
// Read Sprockets README (https://github.com/rails/sprockets#sprockets-directives) for details
// about supported directives.
//
//= require rails-ujs
//= require jquery
//= require jquery.turbolinks
//= require jquery-ui
//= require jquery_ujs  
//= require turbolinks
//= require select2-full
//= require bootstrap
//= require jquery-tablesorter
//= require_tree .
```

manage_devices.coffee:

```
# Place all the behaviors and hooks related to the matching controller here.
# All this logic will automatically be available in application.js.
# You can use CoffeeScript in this file: http://coffeescript.org/
ready = ->
	
	$("table").tablesorter({
    #this will apply the bootstrap theme if "uitheme" widget is included
    #the widgetOptions.uitheme is no longer required to be set
    theme : "blue",
	
    headerTemplate : '{content} {icon}',

    # widget code contained in the jquery.tablesorter.widgets.js file
    # use the zebra stripe widget if you plan on hiding any rows (filter widget)
    widgets : ["uitheme", "columns", "filter", "zebra"],
	
	widgetOptions : {
		filter_reset : 'button.reset'
	}
});
	
$(document).ready(ready)
$(document).on('turbolinks:load', ready)
```

**Comment by shazam1453** [comment]
Ha, figured out it was an issue with some of my spacing once I pasted the code here that wasn't showing in my editor, sorry for opening the issue!!

**Comment by themilkman** [comment]
No problem, thanks for feedback :-)
